#! /bin/bash

# Set environment to run GRASS python package on a Linux system
export GISBASE=/usr/lib/grass64
export PATH="$PATH:$GISBASE/bin:$GISBASE/scripts"
export PYTHONPATH=$GISBASE/etc/python
export GISRC="$HOME/.grassrc6"
export GRASS_PYTHON=python
# for parallel session management, we use process ID (PID) as lock file number:
export GIS_LOCK=$$

python -c "import grass; print(grass)"
